# Generated by Django 5.1.6 on 2025-08-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.URLField(default='https://example.com', max_length=500),
            preserve_default=False,
        ),
    ]
