# Generated by Django 5.1.6 on 2025-08-11 20:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
