# Generated by Django 5.1.6 on 2025-08-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='links/'),
        ),
    ]
